name: recipes
description: Recipe Finder

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  chopper: # ^6.0.0
  logging: ^1.0.2
  cached_network_image: ^3.2.2
  provider: ^6.0.3
  equatable: ^2.0.5
  flutter_slidable: ^2.0.0
  platform: ^3.1.0
  flutter_svg: ^1.1.4
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  build_runner_core: ^7.2.0
  json_serializable: ^6.3.1
  chopper_generator: ^6.0.0
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/recipes1.json
    - assets/recipes2.json
    - assets/images/
